/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_bupin_jnidemo_JniUtil */

#ifndef _Included_com_bupin_jnidemo_JniUtil
#define _Included_com_bupin_jnidemo_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bupin_jnidemo_JniUtil
 * Method:    helloFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_bupin_jnidemo_JniUtil_helloFromC(JNIEnv *env, jobject obj) {
    __android_log_print(ANDROID_LOG_INFO, "MainActivity", "JNI:hello jni");
}

/*
 * Class:     com_bupin_jnidemo_JniUtil
 * Method:    testInt
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL
Java_com_bupin_jnidemo_JniUtil_testInt(JNIEnv *env, jobject obj, jint a, jint b) {
    int i1 = a;
    int i2 = b;
    __android_log_print(ANDROID_LOG_INFO, "MainActivity", "收到的数据:a=%d   b=%d", a, b);
    int c = a + b;
    return c;
}

/*
 * Class:     com_bupin_jnidemo_JniUtil
 * Method:    testBoolean
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_bupin_jnidemo_JniUtil_testBoolean(JNIEnv *env, jobject obj, jboolean b) {
    int flag = (b == JNI_TRUE) ? 1 : 0;
    return (flag == 1) ? JNI_TRUE : JNI_FALSE;
}

/*
 * Class:     com_bupin_jnidemo_JniUtil
 * Method:    testString
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL
Java_com_bupin_jnidemo_JniUtil_testString(JNIEnv *env, jobject obj, jstring s1, jstring s2) {
    const char *str1 = NULL;
    const char *str2 = NULL;
    str1 = env->GetStringUTFChars(s1, 0);
    __android_log_print(ANDROID_LOG_INFO, "MainActivity", "before release JNI: str1 = %s", str1);
    //释放java传递过来jstring里面的在堆上开辟的字符串空间
    env->ReleaseStringUTFChars(s1, str1);
    //  __android_log_print(ANDROID_LOG_INFO, "MainActivity", "after release JNI: c_str1 = %s", str1);

    str2 = env->GetStringUTFChars(s2, 0);
    __android_log_print(ANDROID_LOG_INFO, "MainActivity", "before release JNI: str2 = %s", str2);
    //释放java传递过来jstring里面的在堆上开辟的字符串空间
    env->ReleaseStringUTFChars(s2, str2);

    jstring str = env->NewStringUTF("JNI return String:");
    return str;
}

/*
 * Class:     com_bupin_jnidemo_JniUtil
 * Method:    testArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL
Java_com_bupin_jnidemo_JniUtil_testArray(JNIEnv *env, jobject obj, jintArray arr) {
    jint *p = env->GetIntArrayElements(arr, 0);
    jsize len = env->GetArrayLength(arr);
    __android_log_print(ANDROID_LOG_INFO, "MainActivity", "len=%d", len);
    for (int i = 0; i < len; i++) {
        __android_log_print(ANDROID_LOG_INFO, "MainActivity", "p[%d]=%d\n", i, p[i]);
    }
    env->ReleaseIntArrayElements(arr,p,0);
}

#ifdef __cplusplus
}
#endif
#endif